-- ==========================================================================
-- SOMS Enterprise — Phase 1.75 v2: Health & Recovery Platform
-- Tracking tables for enterprise repairs and history.
-- (Removed generic execute_sql_admin for security).
-- ==========================================================================

-- 1. Expanded Audit History
ALTER TABLE IF EXISTS audit_history 
  ADD COLUMN IF NOT EXISTS objects_scanned INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS objects_skipped INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS run_duration_ms INTEGER DEFAULT 0;

-- 2. Audit Findings Tracking
CREATE TABLE IF NOT EXISTS audit_findings (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  audit_id        UUID REFERENCES audit_history(id) ON DELETE CASCADE,
  module          TEXT NOT NULL,
  issue           TEXT NOT NULL,
  severity        TEXT NOT NULL,
  risk_level      TEXT NOT NULL,
  repairable      BOOLEAN DEFAULT false,
  repair_def_id   TEXT,
  target_objects  JSONB DEFAULT '[]'::jsonb,
  status          TEXT NOT NULL DEFAULT 'pending', -- pending, repaired, ignored
  detected_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  fixed_at        TIMESTAMPTZ
);

ALTER TABLE audit_findings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admin_read_audit_findings" ON audit_findings FOR SELECT USING (auth.uid() IS NOT NULL);

-- 3. Repair Execution History
CREATE TABLE IF NOT EXISTS repair_history (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  finding_id          UUID REFERENCES audit_findings(id) ON DELETE SET NULL,
  repair_def_id       TEXT NOT NULL,
  status              TEXT NOT NULL, -- pending, success, failed, rolled_back
  execution_time_ms   INTEGER,
  rows_affected       INTEGER,
  error_message       TEXT,
  approved_by         UUID REFERENCES auth.users(id),
  executed_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  rollback_executed_at TIMESTAMPTZ
);

ALTER TABLE repair_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "admin_read_repair_history" ON repair_history FOR SELECT USING (auth.uid() IS NOT NULL);

-- 4. Safe DDL Execution Wrapper
-- We use a highly restricted function that ONLY executes when passed an exact payload
-- generated by the Backend Repair Registry, but since the backend uses the Service Role,
-- the Service Role can just execute query via Supabase SDK. 
-- However, if we need `EXPLAIN`, it's easier to run it via RPC if postgREST complains.
CREATE OR REPLACE FUNCTION admin_explain_query(query text)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  explain_result JSONB;
BEGIN
  IF current_role != 'service_role' THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  -- Warning: EXPLAIN can execute functions if they are volatile. 
  -- But since the backend registry controls the query, this is safe.
  EXECUTE 'EXPLAIN (FORMAT JSON) ' || query INTO explain_result;
  RETURN explain_result;
END;
$$;

GRANT EXECUTE ON FUNCTION admin_explain_query TO service_role;
